from aiogram.types import ReplyKeyboardRemove, ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup
import config
import os

kb_remove = ReplyKeyboardRemove(True)

btnWhite = KeyboardButton(config.color_white)
btnGray = KeyboardButton(config.color_gray)
btnRed = KeyboardButton(config.color_red)
btnOrange = KeyboardButton(config.color_orange)
btnYellow = KeyboardButton(config.color_yellow)
btnGreen = KeyboardButton(config.color_green)
btnBlue = KeyboardButton(config.color_blue)
btnHavyBlue = KeyboardButton(config.color_havyblue)
btnPurple = KeyboardButton(config.color_purple)
btnPink = KeyboardButton(config.color_pink)

btnMember = KeyboardButton(config.say_member)
btnCaptain = KeyboardButton(config.say_captain)

kb_ChoiseStatus = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(btnMember, btnCaptain)

btnContinueCaptain = KeyboardButton(config.say_continue_captain)
btnContinueMember = KeyboardButton(config.say_continue_member)

kb_ChoiseContinueStatus = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(btnContinueCaptain, btnContinueMember)

btnContinueLocation = KeyboardButton(config.say_continue_location)
btnStartLaterLocation = KeyboardButton(config.say_start_later_location)

kb_ChoiseActionLocation = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(btnContinueLocation, btnStartLaterLocation)

btnTemMap = KeyboardButton(config.say_get_team_map)
kb_TeamMap = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(btnTemMap)

btnChatWhite = InlineKeyboardButton(config.color_white, url=os.environ.get('CHAT_LINK1'), callback_data='btnChatWhite')
btnChatGray = InlineKeyboardButton(config.color_gray, url=os.environ.get('CHAT_LINK2'), callback_data='btnChatGray')
btnChatRed = InlineKeyboardButton(config.color_red, url=os.environ.get('CHAT_LINK3'), callback_data='btnChatRed')
btnChatOrange = InlineKeyboardButton(config.color_orange, url=os.environ.get('CHAT_LINK4'), callback_data='btnChatOrange')
btnChatYellow = InlineKeyboardButton(config.color_yellow, url=os.environ.get('CHAT_LINK5'), callback_data='btnChatYellow')
btnChatGreen = InlineKeyboardButton(config.color_green, url=os.environ.get('CHAT_LINK6'), callback_data='btnChatGreen')
btnChatBlue = InlineKeyboardButton(config.color_blue, url=os.environ.get('CHAT_LINK7'), callback_data='btnChatBlue')
btnChatHavyBlue = InlineKeyboardButton(config.color_havyblue, url=os.environ.get('CHAT_LINK8'), callback_data='btnChatHavyBlue')
btnChatPurple = InlineKeyboardButton(config.color_purple, url=os.environ.get('CHAT_LINK9'), callback_data='btnChatPurple')
btnChatPink = InlineKeyboardButton(config.color_pink, url=os.environ.get('CHAT_LINK10'), callback_data='btnChatPink')

kb_ChatWhite = InlineKeyboardMarkup().add(btnChatWhite)
kb_ChatGray = InlineKeyboardMarkup().add(btnChatGray)
kb_ChatRed = InlineKeyboardMarkup().add(btnChatRed)
kb_ChatOrange = InlineKeyboardMarkup().add(btnChatOrange)
kb_ChatYellow = InlineKeyboardMarkup().add(btnChatYellow)
kb_ChatGreen = InlineKeyboardMarkup().add(btnChatGreen)
kb_ChatBlue = InlineKeyboardMarkup().add(btnChatBlue)
kb_ChatHavyBlue = InlineKeyboardMarkup().add(btnChatHavyBlue)
kb_ChatPurple = InlineKeyboardMarkup().add(btnChatPurple)
kb_ChatPink = InlineKeyboardMarkup().add(btnChatPink)

kb_ColorCommand = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(btnWhite, btnGray, btnRed).row(btnOrange, btnYellow).row(btnGreen, btnBlue, btnHavyBlue).row(btnPurple, btnPink)

btnContinue = KeyboardButton(config.say_continue)
btnChange = KeyboardButton(config.say_change)

kb_check = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(btnContinue, btnChange)

btnHintOne_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintOne_1')
btnHintOne_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintOne_2')
btnHintOne_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintOne_3')
btnHintOne_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintOne_4')
btnHintOne_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintOne_5')
btnHintOne_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintOne_6')
btnHintOne_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintOne_7')
btnHintOne_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintOne_8')
btnHintOne_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintOne_9')
btnHintOne_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintOne_10')
btnHintOne_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintOne_11')
btnHintOne_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintOne_12')

btnHintTwo_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTwo_1')
btnHintTwo_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTwo_2')
btnHintTwo_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTwo_3')
btnHintTwo_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTwo_4')
btnHintTwo_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTwo_5')
btnHintTwo_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTwo_6')
btnHintTwo_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTwo_7')
btnHintTwo_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTwo_8')
btnHintTwo_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTwo_9')
btnHintTwo_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTwo_10')
btnHintTwo_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTwo_11')
btnHintTwo_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTwo_12')

btnHintThree_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintThree_1')
btnHintThree_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintThree_2')
btnHintThree_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintThree_3')
btnHintThree_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintThree_4')
btnHintThree_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintThree_5')
btnHintThree_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintThree_6')
btnHintThree_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintThree_7')
btnHintThree_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintThree_8')
btnHintThree_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintThree_9')
btnHintThree_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintThree_10')
btnHintThree_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintThree_11')
btnHintThree_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintThree_12')

btnHintFour_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFour_1')
btnHintFour_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFour_2')
btnHintFour_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFour_3')
btnHintFour_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFour_4')
btnHintFour_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFour_5')
btnHintFour_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFour_6')
btnHintFour_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFour_7')
btnHintFour_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFour_8')
btnHintFour_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFour_9')
btnHintFour_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFour_10')
btnHintFour_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFour_11')
btnHintFour_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFour_12')

btnHintFive_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFive_1')
btnHintFive_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFive_2')
btnHintFive_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFive_3')
btnHintFive_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFive_4')
btnHintFive_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFive_5')
btnHintFive_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFive_6')
btnHintFive_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFive_7')
btnHintFive_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFive_8')
btnHintFive_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFive_9')
btnHintFive_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintFive_10')
btnHintFive_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintFive_11')
btnHintFive_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintFive_12')

btnHintSix_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSix_1')
btnHintSix_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSix_2')
btnHintSix_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSix_3')
btnHintSix_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSix_4')
btnHintSix_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSix_5')
btnHintSix_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSix_6')
btnHintSix_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSix_7')
btnHintSix_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSix_8')
btnHintSix_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSix_9')
btnHintSix_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSix_10')
btnHintSix_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSix_11')
btnHintSix_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSix_12')

btnHintSeven_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSeven_1')
btnHintSeven_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSeven_2')
btnHintSeven_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSeven_3')
btnHintSeven_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSeven_4')
btnHintSeven_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSeven_5')
btnHintSeven_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSeven_6')
btnHintSeven_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSeven_7')
btnHintSeven_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSeven_8')
btnHintSeven_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSeven_9')
btnHintSeven_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintSeven_10')
btnHintSeven_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintSeven_11')
btnHintSeven_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintSeven_12')

btnHintEight_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintEight_1')
btnHintEight_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintEight_2')
btnHintEight_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintEight_3')
btnHintEight_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintEight_4')
btnHintEight_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintEight_5')
btnHintEight_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintEight_6')
btnHintEight_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintEight_7')
btnHintEight_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintEight_8')
btnHintEight_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintEight_9')
btnHintEight_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintEight_10')
btnHintEight_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintEight_11')
btnHintEight_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintEight_12')

btnHintNine_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintNine_1')
btnHintNine_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintNine_2')
btnHintNine_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintNine_3')
btnHintNine_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintNine_4')
btnHintNine_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintNine_5')
btnHintNine_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintNine_6')
btnHintNine_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintNine_7')
btnHintNine_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintNine_8')
btnHintNine_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintNine_9')
btnHintNine_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintNine_10')
btnHintNine_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintNine_11')
btnHintNine_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintNine_12')

btnHintTen_1 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTen_1')
btnHintTen_2 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTen_2')
btnHintTen_3 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTen_3')
btnHintTen_4 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTen_4')
btnHintTen_5 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTen_5')
btnHintTen_6 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTen_6')
btnHintTen_7 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTen_7')
btnHintTen_8 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTen_8')
btnHintTen_9 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTen_9')
btnHintTen_10 = InlineKeyboardButton(config.hint_one_coin, callback_data='btnHintTen_10')
btnHintTen_11 = InlineKeyboardButton(config.hint_three_coin, callback_data='btnHintTen_11')
btnHintTen_12 = InlineKeyboardButton(config.hint_five_coin, callback_data='btnHintTen_12')

kb_HintOne_1 = InlineKeyboardMarkup().add(btnHintOne_1, btnHintOne_2, btnHintOne_3)
kb_HintOne_2 = InlineKeyboardMarkup().add(btnHintOne_4, btnHintOne_5, btnHintOne_6)
kb_HintOne_3 = InlineKeyboardMarkup().add(btnHintOne_7, btnHintOne_8, btnHintOne_9)
kb_HintOne_4 = InlineKeyboardMarkup().add(btnHintOne_10, btnHintOne_11, btnHintOne_12)

kb_HintTwo_1 = InlineKeyboardMarkup().add(btnHintTwo_1, btnHintTwo_2, btnHintTwo_3)
kb_HintTwo_2 = InlineKeyboardMarkup().add(btnHintTwo_4, btnHintTwo_5, btnHintTwo_6)
kb_HintTwo_3 = InlineKeyboardMarkup().add(btnHintTwo_7, btnHintTwo_8, btnHintTwo_9)
kb_HintTwo_4 = InlineKeyboardMarkup().add(btnHintTwo_10, btnHintTwo_11, btnHintTwo_12)

kb_HintThree_1 = InlineKeyboardMarkup().add(btnHintThree_1, btnHintThree_2, btnHintThree_3)
kb_HintThree_2 = InlineKeyboardMarkup().add(btnHintThree_4, btnHintThree_5, btnHintThree_6)
kb_HintThree_3 = InlineKeyboardMarkup().add(btnHintThree_7, btnHintThree_8, btnHintThree_9)
kb_HintThree_4 = InlineKeyboardMarkup().add(btnHintThree_10, btnHintThree_11, btnHintThree_12)

kb_HintFour_1 = InlineKeyboardMarkup().add(btnHintFour_1, btnHintFour_2, btnHintFour_3)
kb_HintFour_2 = InlineKeyboardMarkup().add(btnHintFour_4, btnHintFour_5, btnHintFour_6)
kb_HintFour_3 = InlineKeyboardMarkup().add(btnHintFour_7, btnHintFour_8, btnHintFour_9)
kb_HintFour_4 = InlineKeyboardMarkup().add(btnHintFour_10, btnHintFour_11, btnHintFour_12)

kb_HintFive_1 = InlineKeyboardMarkup().add(btnHintFive_1, btnHintFive_2, btnHintFive_3)
kb_HintFive_2 = InlineKeyboardMarkup().add(btnHintFive_4, btnHintFive_5, btnHintFive_6)
kb_HintFive_3 = InlineKeyboardMarkup().add(btnHintFive_7, btnHintFive_8, btnHintFive_9)
kb_HintFive_4 = InlineKeyboardMarkup().add(btnHintFive_10, btnHintFive_11, btnHintFive_12)

kb_HintSix_1 = InlineKeyboardMarkup().add(btnHintSix_1, btnHintSix_2, btnHintSix_3)
kb_HintSix_2 = InlineKeyboardMarkup().add(btnHintSix_4, btnHintSix_5, btnHintSix_6)
kb_HintSix_3 = InlineKeyboardMarkup().add(btnHintSix_7, btnHintSix_8, btnHintSix_9)
kb_HintSix_4 = InlineKeyboardMarkup().add(btnHintSix_10, btnHintSix_11, btnHintSix_12)

kb_HintSeven_1 = InlineKeyboardMarkup().add(btnHintSeven_1, btnHintSeven_2, btnHintSeven_3)
kb_HintSeven_2 = InlineKeyboardMarkup().add(btnHintSeven_4, btnHintSeven_5, btnHintSeven_6)
kb_HintSeven_3 = InlineKeyboardMarkup().add(btnHintSeven_7, btnHintSeven_8, btnHintSeven_9)
kb_HintSeven_4 = InlineKeyboardMarkup().add(btnHintSeven_10, btnHintSeven_11, btnHintSeven_12)

kb_HintEight_1 = InlineKeyboardMarkup().add(btnHintEight_1, btnHintEight_2, btnHintEight_3)
kb_HintEight_2 = InlineKeyboardMarkup().add(btnHintEight_4, btnHintEight_5, btnHintEight_6)
kb_HintEight_3 = InlineKeyboardMarkup().add(btnHintEight_7, btnHintEight_8, btnHintEight_9)
kb_HintEight_4 = InlineKeyboardMarkup().add(btnHintEight_10, btnHintEight_11, btnHintEight_12)

kb_HintNine_1 = InlineKeyboardMarkup().add(btnHintNine_1, btnHintNine_2, btnHintNine_3)
kb_HintNine_2 = InlineKeyboardMarkup().add(btnHintNine_4, btnHintNine_5, btnHintNine_6)
kb_HintNine_3 = InlineKeyboardMarkup().add(btnHintNine_7, btnHintNine_8, btnHintNine_9)
kb_HintNine_4 = InlineKeyboardMarkup().add(btnHintNine_10, btnHintNine_11, btnHintNine_12)

kb_HintTen_1 = InlineKeyboardMarkup().add(btnHintTen_1, btnHintTen_2, btnHintTen_3)
kb_HintTen_2 = InlineKeyboardMarkup().add(btnHintTen_4, btnHintTen_5, btnHintTen_6)
kb_HintTen_3 = InlineKeyboardMarkup().add(btnHintTen_7, btnHintTen_8, btnHintTen_9)
kb_HintTen_4 = InlineKeyboardMarkup().add(btnHintTen_10, btnHintTen_11, btnHintTen_12)